export const FEED_START: "FEED_START" = "FEED_START";
export const FEED_SUCCESS: "FEED_SUCCESS" = "FEED_SUCCESS";
export const FEED_ERROR: "FEED_ERROR" = "FEED_ERROR";
export const FEED_CLOSED: "FEED_CLOSED" = "FEED_CLOSED";
export const FEED_CLOSE: "FEED_CLOSE" = "FEED_CLOSE";
export const FEED_GET_MESSAGE: "FEED_GET_MESSAGE" = "FEED_GET_MESSAGE";

export const ORDER_HISTORY_START: "ORDER_HISTORY_START" = "ORDER_HISTORY_START";
export const ORDER_HISTORY_SUCCESS: "ORDER_HISTORY_SUCCESS" =
  "ORDER_HISTORY_SUCCESS";
export const ORDER_HISTORY_ERROR: "ORDER_HISTORY_ERROR" = "ORDER_HISTORY_ERROR";
export const ORDER_HISTORY_CLOSED: "ORDER_HISTORY_CLOSED" =
  "ORDER_HISTORY_CLOSED";
export const ORDER_HISTORY_CLOSE: "ORDER_HISTORY_CLOSE" = "ORDER_HISTORY_CLOSE";
export const ORDER_HISTORY_GET_MESSAGE: "ORDER_HISTORY_GET_MESSAGE" =
  "ORDER_HISTORY_GET_MESSAGE";
